name: notebook
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+3

  # get_it: ^5.0.6
  flash: ^1.3.2
  path_provider: ^1.6.27
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
